"use client";
import { usePathname } from "next/navigation";

export default function Head({ params }: { params: { slug: string } }) {
  const pathname = usePathname();
  const title = pathname
    ?.split("/")
    .pop()
    ?.replace(/\b[a-z]/, t => t.toUpperCase());
    
  return (
    <>
      <title>{title || 'Home'}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
